package empleados;
// Generated 29 may 2024 12:03:54 by Hibernate Tools 5.6.14.Final

/**
 * Departamento generated by hbm2java
 */
public class Departamento implements java.io.Serializable {

	private Integer idDep;
	private String nombre;
	private String localidad;

	public Departamento() {
	}

	public Departamento(String nombre, String localidad) {
		this.nombre = nombre;
		this.localidad = localidad;
	}

	public Integer getIdDep() {
		return this.idDep;
	}

	public void setIdDep(Integer idDep) {
		this.idDep = idDep;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

}
