package empleados;
// Generated 29 may 2024 12:03:54 by Hibernate Tools 5.6.14.Final

import java.util.Date;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private Integer idEmp;
	private String apellido;
	private String oficio;
	private Date fechaAlta;
	private Long salario;
	private Long comision;
	private Integer idDep;

	public Empleado() {
	}

	public Empleado(String apellido, String oficio, Date fechaAlta, Long salario, Long comision, Integer idDep) {
		this.apellido = apellido;
		this.oficio = oficio;
		this.fechaAlta = fechaAlta;
		this.salario = salario;
		this.comision = comision;
		this.idDep = idDep;
	}

	public Integer getIdEmp() {
		return this.idEmp;
	}

	public void setIdEmp(Integer idEmp) {
		this.idEmp = idEmp;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getOficio() {
		return this.oficio;
	}

	public void setOficio(String oficio) {
		this.oficio = oficio;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Long getSalario() {
		return this.salario;
	}

	public void setSalario(Long salario) {
		this.salario = salario;
	}

	public Long getComision() {
		return this.comision;
	}

	public void setComision(Long comision) {
		this.comision = comision;
	}

	public Integer getIdDep() {
		return this.idDep;
	}

	public void setIdDep(Integer idDep) {
		this.idDep = idDep;
	}

}
